//PRODUCT fetch ACTION TYPE
export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const FETCH_ALL_FAIL = 'FETCH_ALL_FAIL'

//search products
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL'
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST'
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_REQUEST'

//fetch single product
export const FETCH_SINGLE_REQUEST = 'FETCH_SINGLE_REQUEST'
export const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS'
export const FETCH_SINGLE_FAIL = 'FETCH_SINGLE_FAIL'

//fetch featured products
export const FETCH_FEATURED_REQUEST = 'FETCH_FEATURED_REQUEST'
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS'
export const FETCH_FEATURED_FAIL = 'FETCH_FEATURED_FAIL'

//review products
export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET'

//CART ACTIONTYPES
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'
export const CART_SAVE_SHIPPING_DETAILS = 'CART_SAVE_SHIPPING_DETAILS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

//SAVE ITEM ACTIONTYPES
export const SAVE_ADD_ITEM = 'SAVE_ADD_ITEM'
export const SAVE_REMOVE_ITEM = 'SAVE_REMOVE_ITEM'
export const SAVE_CLEAR_ITEM = 'SAVE_CLEAR_ITEM'
export const SAVE_REQUEST = 'SAVE_REQUEST'
export const SAVE_SUCCESS = 'SAVE_SUCCESS'
export const SAVE_FAIL = 'SAVE_FAIL'


//USER LOGIN ACTION
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

//USER LOGIN ACTION
export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL'

//USER REGISTER ACTION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

//USER REGISTER DETAILS ACTION
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

//USER UPDATE PROFILE ACTION
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

//ORDER ACTION
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

//ORDER DETAIL
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

//ORDER PAY
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

//ORDER LIST
export const ORDER_HISTORY_REQUEST = 'ORDER_HISTORY_REQUEST'
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS'
export const ORDER_HISTORY_FAIL = 'ORDER_HISTORY_FAIL'
export const ORDER_HISTORY_RESET = 'ORDER_HISTORY_RESET'

//mailinglist
export const MAIL_REGISTER_REQUEST = 'MAIL_REGISTER_REQUEST'
export const MAIL_REGISTER_SUCCESS = 'MAIL_REGISTER_SUCCESS'
export const MAIL_REGISTER_FAIL = 'MAIL_REGISTER_FAIL'
export const MAIL_SAVE_GENDER_METHOD = 'MAIL_SAVE_GENDER_METHOD'

